### ISSUE TITLE
verification of fwd vol skew

### ISSUE THREAD

**Issue by techbackpack** [jcfrei/Heston#2]
Greetings Jonathan -

  I have been testing your function a little more and I wanted to verify with you that I am seeing the correct behavior.  Please let me know if I am seeing the correct behavior.  I pulled the Options Data for US Equity ticker XOM.  I setup a calibration and arrived at the following:

Current Variance:  +0.071
Theta:  +0.066
Rho:  -0.999
Kappa:  +5.382
Sigma:  +0.500

I then priced a selection of strikes assuming Maturity of .5 Years.  After pricing, I backed out the Black Scholes Implied.  This is a picture verifying my results.  I think it looks correct.  (Rho is nearly -1).

![current_implied](https://cloud.githubusercontent.com/assets/16579609/13803117/859a8ad8-eb18-11e5-88ad-0cf1e79b94cd.jpg)

After this I tried to run another test.  I simulated a set of log-normal fwd prices .25 years away.  I assumed in each Price Scenario, 2500 of them using Monte Carlo, that I buy the current ATM strike.  In this case the price is currently 82.80, so the Strike in each case is 83.  For each Fwd Price, I used your model to back out the Option Price.  Again, I backed out the implied volatility.  I show the graph below:

![forward_implied](https://cloud.githubusercontent.com/assets/16579609/13803232/aefbfc12-eb19-11e5-8b05-c2bc12849772.jpg)

However on this graph, I want to verify what may be correct- but feels counter-intuitive:  here we are seeing forward implied volatility which is lower for forward spot prices.  Is this correct?  This runs counter to my expectation.  I tried to rationalize why this would be and decided to post here to get your feedback.  Please let me know your thoughts.

**Comment by techbackpack** [comment]
Jonathan -

I believe I have the logical explanation and it makes sense to me now.  Please let me know if you agree here.  In this forward-space, .25 years away - if the spot price has dropped from around 83 to 70, then the ATM implied volatility will increase.

However, as I specified in my second experiment / second graph above, I purchased ATM options at time of origination.  Thus I am referring to an option which relative to the new Fwd Spot price of 70 ----- .25 years later ----- is now 13 handles above the new Fwd ATM strike.  And this 83 strike should have an implied vol lower than the Fwd Spot implied vol.

Hence, the lower the fwd spot, the higher the origination ATM implied vol---
and --- the higher the fwd spot, the lower the origination ATM implied vol.
This is certainly counterintuitive and I believe my explanation here is coherent.
If you agree with me let's close the issue.  I'd like to hear your comments if you have anything to add.

Best Wishes!

**Comment by jcfrei** [comment]
Hello nehalem42, I'm not 100% sure I fully understood your setup. At first you are plotting implied volatilities for different strikes and then you are plotting implied volatilities for different spots? As a result the term structures appear almost mirrored - taking into account different maturities of (0.25 and 0.5). Might this be an explanation?

Different strikes
![differentstrikes](https://cloud.githubusercontent.com/assets/523261/13852620/3b2cd4f0-ec63-11e5-9776-b23b8cf9b207.png)

Different spots
![differentspots](https://cloud.githubusercontent.com/assets/523261/13852623/3f02e2f4-ec63-11e5-97c2-9a14e9a080ea.png)

**Comment by techbackpack** [comment]
We are certainly plotting the same features in our graphs.  Thank you for uploading the 3D-version illustrating this behaviour.  I find this fascinating and still mildly counter-intuitive.  The net effect is that we have arrived at the proximal starting point for a discussion on stick-to-strike vs sticky delta for implied volatility per:

https://en.wikipedia.org/wiki/Volatility_smile

Thank you for your time Jonathan.  I am closing the Issue Thread and I welcome all future discussions.
